// products.js - База данных товаров
const productsData = [
    // Мёд
    { id: 1, category: "honey", subcategory: "flower", name: "Цветочный мёд", price: 850, rating: 4.8, description: "Лёгкий, ароматный мёд, собранный с луговых цветов разнотравья. Идеально подходит для чаепития.", characteristics: { "Вес": "1 кг", "Сорт": "Полифлорный", "Кристаллизация": "Мелкозернистая" }, images: ["🌼", "🍯"] },
    { id: 2, category: "honey", subcategory: "buckwheat", name: "Гречишный мёд", price: 950, rating: 4.9, description: "Тёмный, насыщенный мёд с характерным терпким вкусом и лёгкой горчинкой. Богат железом.", characteristics: { "Вес": "1 кг", "Сорт": "Монофлорный", "Цвет": "Тёмно-коричневый" }, images: ["🌾", "🍯"] },
    { id: 3, category: "honey", subcategory: "linden", name: "Липовый мёд", price: 1100, rating: 5.0, description: "Светлый мёд с нежным ароматом липы. Традиционно ценится при простудных заболеваниях.", characteristics: { "Вес": "1 кг", "Сорт": "Монофлорный", "Вкус": "Сладкий, слегка терпкий" }, images: ["🍃", "🍯"] },
    { id: 4, category: "honey", subcategory: "acacia", name: "Акациевый мёд", price: 1300, rating: 4.7, description: "Очень светлый, жидкий мёд. Долго не кристаллизуется. Обладает тонким цветочным ароматом.", characteristics: { "Вес": "1 кг", "Сорт": "Монофлорный", "Кристаллизация": "Медленная" }, images: ["🌳", "🍯"] },
    // Продукция пчеловодства
    { id: 5, category: "bee-products", subcategory: "wax", name: "Пчелиный воск", price: 600, rating: 4.5, description: "Натуральный пчелиный воск высшего сорта. Идеален для косметики и свечей.", characteristics: { "Вес": "200 г", "Сорт": "Вощина", "Цвет": "Светло-жёлтый" }, images: ["🕯️", "🟡"] },
    { id: 6, category: "bee-products", subcategory: "propolis", name: "Прополис", price: 750, rating: 4.9, description: "Мощный природный антисептик. Используется в народной медицине и здоровом питании.", characteristics: { "Вес": "50 г", "Форма": "Кусковая", "Происхождение": "Алтай" }, images: ["🟤", "🌿"] },
    { id: 7, category: "bee-products", subcategory: "perga", name: "Перга (пчелиный хлеб)", price: 900, rating: 4.6, description: "Пыльца, ферментированная пчёлами. Содержит витамины, аминокислоты и минералы.", characteristics: { "Вес": "200 г", "Форма": "Гранулы", "Вкус": "Кисло-сладкий" }, images: ["🟠", "🍞"] },
    { id: 8, category: "bee-products", subcategory: "royal-jelly", name: "Маточное молочко", price: 2500, rating: 5.0, description: "Элитный продукт пчеловодства. Мощный иммуномодулятор и биостимулятор.", characteristics: { "Вес": "10 г", "Хранение": "Морозильник", "Форма": "Нативное" }, images: ["⚪", "👑"] },
    // Инвентарь
    { id: 9, category: "equipment", subcategory: "smoker", name: "Дымарь пасечный", price: 1500, rating: 4.4, description: "Классический дымарь из нержавеющей стали с защитной решёткой от ожогов.", characteristics: { "Материал": "Нержавейка", "Диаметр": "100 мм", "Комплектация": "Два меха" }, images: ["💨", "🪵"] },
    { id: 10, category: "equipment", subcategory: "hive", name: "Улей Дадан 10-р", price: 5500, rating: 4.3, description: "Деревянный улей из сухой сосны. Включает корпус, дно, крышу и магазины.", characteristics: { "Материал": "Сосна", "Тип": "Дадан", "Покраска": "Включена" }, images: ["🏠", "🪵"] },
    { id: 11, category: "equipment", subcategory: "frames", name: "Рамки дадановские (10 шт)", price: 800, rating: 4.5, description: "Гнездовые рамки с разделителями. Изготовлены из качественной древесины.", characteristics: { "Количество": "10 шт", "Размер": "435x300 мм", "Тип": "Гнездовые" }, images: ["🟫", "📐"] },
    { id: 12, category: "equipment", subcategory: "extractor", name: "Медогонка 3-х рамочная", price: 12000, rating: 4.8, description: "Радиальная медогонка с нержавеющим баком и надежным приводом.", characteristics: { "Материал бака": "Нержавейка", "Тип": "Радиальная", "Привод": "Ручной" }, images: ["⚙️", "🥣"] }
];